### PR TITLE
Typo fixup

### PR DESCRIPTION
**Pull request by numbqq**
Khadas VIM is an Open Source DIY Box manufactured by Shenzhen Wesion NOT 'Tomato'

### CODE REVIEW

**Comment by numbqq** [comment]
This PR fixup a typo for Khadas VIM manufactur. Can you merge it and push to upstream?

**Comment by superna9999** [comment]
Yes sorry for the typo, I’ll push it when available !

**Comment by superna9999** [comment]
@numbqq Can I have a proper Sign-off full name so I can push the commit upstream ?

**Comment by superna9999** [comment]
Ignore, I sent the patch at https://lists.denx.de/pipermail/u-boot/2018-January/315613.html

**Comment by superna9999** [comment]
Well, it was fast, applied !

**Comment by numbqq** [comment]
Nice! Thank you Neil!

**Pull request merged**
